apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: aGp3Z2ViaWU=
  CLOUDINARY_KEY: MTY3Mzg3MzcxMjY3Njgy
  CLOUDINARY_SECRET: MmJRTFk1N2U2YVFmSi14Yw==
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljbUYyYVc1a1lYSTNOemc0SWl3aVlTSTZJbU50YzIxek16Z3llREUxYkRneWVITTJlbUkxWVRsdGJqY2lmUS5YS0xYYnZ4dEk0S3FVZ3dXYUNackx3
  DB_URL: bW9uZ29kYitzcnY6Ly9ha3VsYXJhdmluZGFyNTVfZGJfdXNlcjpJTUUwZEcydEprT2JNcU9UQGNsdXN0ZXIwLnl4YXFrYXoubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjAgfCBiYXNlNjQKZWNobyAtbiBtb25nb2RiK3NydjovL2FrdWxhcmF2aW5kYXI1NV9kYl91c2VyOklNRTBkRzJ0SmtPYk1xT1RAY2x1c3RlcjAueXhhcWthei5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
